name: Deploy

on:
  schedule:
    - cron: '0 18 * * 0/2' # 3am JST every other Sunday (UTC: 18:00 every other Saturday)
  workflow_dispatch:

jobs:
  curl:
    name: Kick deploy hook
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -X POST '${{ secrets.DEPLOY_HOOK_URL }}'
